export const HOME_LOGIN_BEGIN = 'HOME_LOGIN_BEGIN';
export const HOME_LOGIN_SUCCESS = 'HOME_LOGIN_SUCCESS';
export const HOME_LOGIN_FAILURE = 'HOME_LOGIN_FAILURE';
export const HOME_LOGIN_DISMISS_ERROR = 'HOME_LOGIN_DISMISS_ERROR';
