export const ROOM_ADMIN_FETCH_PUBLIC_ROOMS_BEGIN = 'ROOM_ADMIN_FETCH_PUBLIC_ROOMS_BEGIN';
export const ROOM_ADMIN_FETCH_PUBLIC_ROOMS_SUCCESS = 'ROOM_ADMIN_FETCH_PUBLIC_ROOMS_SUCCESS';
export const ROOM_ADMIN_FETCH_PUBLIC_ROOMS_FAILURE = 'ROOM_ADMIN_FETCH_PUBLIC_ROOMS_FAILURE';
export const ROOM_ADMIN_FETCH_PUBLIC_ROOMS_DISMISS_ERROR = 'ROOM_ADMIN_FETCH_PUBLIC_ROOMS_DISMISS_ERROR';
export const ROOM_ADMIN_CREATE_ROOM_BEGIN = 'ROOM_ADMIN_CREATE_ROOM_BEGIN';
export const ROOM_ADMIN_CREATE_ROOM_SUCCESS = 'ROOM_ADMIN_CREATE_ROOM_SUCCESS';
export const ROOM_ADMIN_CREATE_ROOM_FAILURE = 'ROOM_ADMIN_CREATE_ROOM_FAILURE';
export const ROOM_ADMIN_CREATE_ROOM_DISMISS_ERROR = 'ROOM_ADMIN_CREATE_ROOM_DISMISS_ERROR';
